# curriculum_validator.py
# Authentic Syntax Validator / True-False challenge bank for Python, Java, and SQL

from curriculum_builder import create_bool_q

def get_python_validator():
    return {
        "Beginner": {
            "1": [
                create_bool_q("In Python, variable names can start with a digit (e.g., 2score = 100).",
                              "2score = 100", "False",
                              "Think about Python variable naming rules.", "Identifiers cannot begin with a number.",
                              "False: Python identifiers must start with a letter (a-z, A-Z) or an underscore (_), never a digit."),
                create_bool_q("Evaluating float division 10 / 2 in Python 3 returns a float (5.0).",
                              "result = 10 / 2\nprint(type(result))", "True",
                              "Single slash always performs true floating-point division in Python 3.", "Result has a decimal point.",
                              "True: The single slash / operator in Python 3 always yields a float, so 10 / 2 is 5.0."),
                create_bool_q("Adding an integer and a numeric string directly using '+' (e.g., 5 + '5') is allowed in Python.",
                              "val = 5 + '5'", "False",
                              "Python is strongly typed and does not implicitly coerce strings to numbers.", "Raises TypeError.",
                              "False: Python raises a TypeError: unsupported operand type(s) for +: 'int' and 'str'."),
                create_bool_q("An empty string '' evaluates to False in boolean context.",
                              "bool('') == False", "True",
                              "Empty sequences have falsy truth values.", "bool('') evaluates to False.",
                              "True: In Python, empty collections and strings '' evaluate to False (falsy)."),
                create_bool_q("Python is case-sensitive, meaning 'score' and 'Score' are distinct variables.",
                              "score = 10\nScore = 20\nprint(score != Score)", "True",
                              "Identifiers with different capitalization are treated separately.", "Capital S makes it unique.",
                              "True: Python is strictly case-sensitive; score and Score reside in different namespace slots.")
            ],
            "2": [
                create_bool_q("Python strings are immutable and cannot have individual characters modified in-place.",
                              "s = 'hello'\ns[0] = 'H'  # Allowed?", "False",
                              "Can you reassign a character by index?", "Raises TypeError: 'str' object does not support item assignment.",
                              "False: Strings in Python are immutable; attempting in-place item assignment raises a TypeError."),
                create_bool_q("Negative indexing is valid in Python, where [-1] accesses the last element.",
                              "msg = 'Python'\nprint(msg[-1] == 'n')", "True",
                              "Negative indices count backwards from the end.", "Index -1 refers to the final character.",
                              "True: Negative indices count from the end of sequences; 'Python'[-1] is indeed 'n'."),
                create_bool_q("The .strip() method modifies the original string in-place.",
                              "name = '  neo  '\nname.strip()\nprint(name == 'neo')", "False",
                              "Strings are immutable; methods return a new string.", "The variable 'name' remains unchanged.",
                              "False: Because strings are immutable, .strip() returns a new string; it does not mutate 'name'."),
                create_bool_q("String multiplication 'Ha' * 3 produces 'HaHaHa'.",
                              "print('Ha' * 3 == 'HaHaHa')", "True",
                              "Multiplying a string by an integer repeats it.", "Repeats 3 times.",
                              "True: The * operator on a string and an integer repeats the string that many times."),
                create_bool_q("The 'in' operator can test for substring membership in a string.",
                              "print('cat' in 'caterpillar')", "True",
                              "Checks if the sequence occurs inside.", "'cat' is at the start.",
                              "True: 'cat' is a contiguous substring of 'caterpillar', so the expression evaluates to True.")
            ],
            "3": [
                create_bool_q("In Python, 0, None, and empty list [] all evaluate to False in an if statement.",
                              "if not 0 and not None and not []:\n    # Reached?", "True",
                              "Zero, None, and empty containers are all falsy.", "All three conditions are falsy.",
                              "True: In Python, 0, None, and [] are all falsy values."),
                create_bool_q("The '==' operator checks object identity (same memory address), while 'is' checks value equality.",
                              "a = [1]; b = [1]\nprint(a is b)", "False",
                              "Which operator checks memory location?", "'is' checks identity; '==' checks value.",
                              "False: '==' checks value equality, whereas 'is' checks identity (same memory address)."),
                create_bool_q("The condition '10 < x < 20' is valid chained comparison syntax in Python.",
                              "x = 15\nif 10 < x < 20:\n    print('Valid')", "True",
                              "Python supports mathematical chained comparisons.", "Equivalent to 10 < x and x < 20.",
                              "True: Python natively supports chained comparisons like 10 < x < 20 without explicit 'and'."),
                create_bool_q("The expression 'not False or False' evaluates to False.",
                              "print(not False or False)", "False",
                              "'not False' evaluates to True.", "True or False is True.",
                              "False: 'not False' evaluates to True, and 'True or False' evaluates to True, not False."),
                create_bool_q("An elif clause can exist without a preceding if statement.",
                              "elif x > 5:\n    print('Valid?')", "False",
                              "Can elif start a conditional block alone?", "Must follow an 'if'.",
                              "False: An 'elif' statement must follow an initial 'if' statement; it cannot stand alone.")
            ],
            "4": [
                create_bool_q("List .append() modifies the list in-place and returns the updated list.",
                              "nums = [1, 2]\nres = nums.append(3)\nprint(res == [1, 2, 3])", "False",
                              "What do mutating list methods return?", "They return None.",
                              "False: .append() mutates the list in-place and returns None, so res is None."),
                create_bool_q("A tuple with a single element requires a trailing comma, e.g. (42,).",
                              "t = (42,)\nprint(type(t) is tuple)", "True",
                              "Without a comma, (42) is just parenthesized int.", "Trailing comma creates the tuple.",
                              "True: Without a trailing comma, (42) is simply an integer surrounded by parentheses."),
                create_bool_q("Python lists can contain elements of mixed data types.",
                              "mixed = [1, 'two', 3.0, True, [4, 5]]", "True",
                              "Are Python lists homogeneous or heterogeneous?", "Python lists allow any object types.",
                              "True: Python lists are heterogeneous and can store arbitrary object types concurrently."),
                create_bool_q("Tuples support .pop() and .append() just like lists.",
                              "t = (1, 2)\nt.append(3)", "False",
                              "Are tuples mutable?", "Tuples are immutable sequences.",
                              "False: Tuples are immutable and do not have .append(), .pop(), or .extend() methods."),
                create_bool_q("Slicing a list nums[:] creates a shallow copy of the list.",
                              "a = [1, 2]\nb = a[:]\nprint(a is not b and a == b)", "True",
                              "Slicing produces a new list object.", "Different identity, same contents.",
                              "True: Full slice a[:] creates a new list with identical elements (shallow copy).")
            ]
        },
        "Intermediate": {
            "1": [
                create_bool_q("In a for...else loop, the else block executes ONLY if the loop completed without hitting a break.",
                              "for i in range(3):\n    pass\nelse:\n    print('Done')", "True",
                              "Loop else clause behavior.", "Runs when loop terminates naturally.",
                              "True: The loop's 'else' branch runs upon normal iteration completion and is skipped if broken out of."),
                create_bool_q("Calling range(5) generates all numbers from 0 up to and including 5.",
                              "print(5 in range(5))", "False",
                              "Is the stop value inclusive or exclusive?", "Stop parameter is strictly exclusive.",
                              "False: range(start, stop) is exclusive of the stop value; range(5) yields 0, 1, 2, 3, 4."),
                create_bool_q("The 'continue' statement immediately exits the entire loop.",
                              "for i in range(3):\n    continue", "False",
                              "Does continue abort the loop or skip to the next iteration?", "break exits; continue skips.",
                              "False: 'continue' skips the remainder of the current iteration, while 'break' exits the loop."),
                create_bool_q("The enumerate() function returns tuples of (index, item).",
                              "for idx, val in enumerate(['a']):\n    print(idx == 0 and val == 'a')", "True",
                              "Index is the first unpacked element.", "Yields pair (0, 'a').",
                              "True: enumerate(iterable) produces tuples containing the zero-based count and value."),
                create_bool_q("Modifying a list while directly iterating over it with a for loop can cause skipped elements.",
                              "nums = [1, 2, 3]\nfor n in nums:\n    nums.remove(n)", "True",
                              "List size changes alter internal iterator indices.", "Mutating during iteration shifts items.",
                              "True: Mutating a list while iterating over it shifts indices and leads to skipped elements or bugs.")
            ],
            "2": [
                create_bool_q("A Python function without an explicit 'return' statement implicitly returns None.",
                              "def greet():\n    print('Hi')\nprint(greet() is None)", "True",
                              "Default return value of functions.", "Returns None.",
                              "True: When execution falls off the end of a function without return, Python returns None."),
                create_bool_q("Using a mutable object (like a list) as a default argument creates a shared object across calls.",
                              "def add(x, lst=[]):\n    lst.append(x)\n    return lst", "True",
                              "Default argument expressions are evaluated once when function is defined.", "Shared across calls.",
                              "True: Default arguments are evaluated once at definition time, making mutable defaults shared."),
                create_bool_q("In Python, positional arguments can be placed AFTER keyword arguments in a function call.",
                              "func(a=1, 2)", "False",
                              "Can non-keyword argument follow keyword argument?", "SyntaxError: positional argument follows keyword argument.",
                              "False: Positional arguments must strictly precede all keyword arguments in Python function calls."),
                create_bool_q("A lambda function in Python can contain multiple expressions separated by semicolons.",
                              "f = lambda x: print(x); x * 2", "False",
                              "Lambda body syntax limitation.", "Lambdas are restricted to a single expression.",
                              "False: Python lambda functions can only contain a single expression whose result is returned."),
                create_bool_q("The *args syntax collects extra positional arguments into a tuple.",
                              "def f(*args):\n    return type(args) is tuple", "True",
                              "What type is args inside the function?", "It is an immutable tuple.",
                              "True: *args bundles variable positional arguments into a tuple.")
            ],
            "3": [
                create_bool_q("Python dictionary keys must be immutable / hashable objects.",
                              "d = {[1, 2]: 'val'}", "False",
                              "Can lists be used as dictionary keys?", "Lists are unhashable.",
                              "False: Dictionary keys must implement __hash__ and be immutable; lists raise TypeError: unhashable type."),
                create_bool_q("Accessing a non-existent key in a dict via d.get('key', 'default') raises a KeyError.",
                              "d = {'a': 1}\nres = d.get('b', 0)", "False",
                              "Does .get() raise an exception?", ".get() returns the fallback default instead of error.",
                              "False: .get(key, default) safely returns the default value without raising KeyError."),
                create_bool_q("Set objects in Python automatically eliminate duplicate elements.",
                              "s = set([1, 2, 2, 3])\nprint(len(s) == 3)", "True",
                              "Sets only contain unique elements.", "Duplicates are discarded.",
                              "True: Sets enforce mathematical uniqueness, automatically stripping duplicate values."),
                create_bool_q("In Python 3.7+, standard dictionaries preserve element insertion order.",
                              "d = {'x': 1, 'y': 2}\nprint(list(d.keys()) == ['x', 'y'])", "True",
                              "Insertion order retention in modern Python.", "Guaranteed as language spec.",
                              "True: As of Python 3.7, dicts are officially guaranteed to maintain insertion order."),
                create_bool_q("Two sets can be combined using the union operator '|'.",
                              "s1 = {1}; s2 = {2}\nprint(s1 | s2 == {1, 2})", "True",
                              "Bitwise OR acts as set union.", "{1} | {2} produces {1, 2}.",
                              "True: The pipe | operator performs set union in Python.")
            ],
            "4": [
                create_bool_q("List comprehensions are generally faster than equivalent manual for-loop append operations.",
                              "[x * 2 for x in range(1000)]", "True",
                              "Comprehensions execute in optimized C-level bytecode.", "Avoids attribute lookup overhead.",
                              "True: List comprehensions run at C-speed in Python bytecode, outperforming manual append() loops."),
                create_bool_q("The 'finally' block in a try-except structure is skipped if an exception is caught.",
                              "try:\n    1/0\nexcept:\n    pass\nfinally:\n    # Runs?", "False",
                              "When does finally execute?", "finally always runs regardless of exceptions.",
                              "False: The 'finally' clause is guaranteed to execute whether an exception occurred, was caught, or was not."),
                create_bool_q("A generator function uses the 'yield' keyword instead of 'return'.",
                              "def gen():\n    yield 1", "True",
                              "Keyword that turns a function into a generator.", "yield pauses execution.",
                              "True: Any function containing the 'yield' keyword returns a generator object when called."),
                create_bool_q("In Python, isinstance(True, int) evaluates to True.",
                              "print(isinstance(True, int))", "True",
                              "Is bool a subclass of int in Python?", "bool inherits from int.",
                              "True: In Python, bool is a subclass of int; True has integer value 1 and False has 0."),
                create_bool_q("A function defined inside another function cannot access the outer function's variables.",
                              "def outer():\n    x = 10\n    def inner(): return x", "False",
                              "Think about closures and lexical scoping.", "Inner functions can read enclosing scope.",
                              "False: Python functions support lexical closures and can access variables from enclosing scopes.")
            ]
        },
        "Advanced": {
            "1": [
                create_bool_q("In Python, all classes implicitly inherit from the base 'object' class in Python 3.",
                              "class Foo: pass\nprint(issubclass(Foo, object))", "True",
                              "Root of the Python type hierarchy.", "Every new-style class inherits from object.",
                              "True: In Python 3, all user-defined classes implicitly subclass 'object'."),
                create_bool_q("The '__init__' method is responsible for memory allocation of the object instance.",
                              "def __init__(self): pass", "False",
                              "Which method allocates memory vs initializes state?", "__new__ allocates; __init__ initializes.",
                              "False: __new__ allocates the instance memory; __init__ merely initializes attributes on the allocated instance."),
                create_bool_q("Python supports multiple inheritance using the C3 Linearization (MRO) algorithm.",
                              "class C(A, B): pass", "True",
                              "Can a class inherit from more than one parent?", "MRO resolves diamond inheritance.",
                              "True: Python supports multiple inheritance, resolving method lookups via the C3 MRO algorithm."),
                create_bool_q("Static methods defined with @staticmethod receive 'self' as their first argument.",
                              "@staticmethod\ndef calculate(self, x): pass", "False",
                              "Do static methods take an instance reference?", "They take no implicit first argument.",
                              "False: @staticmethod does not receive an implicit self or cls argument; it behaves like a regular function."),
                create_bool_q("The __str__ method is meant to be human-readable, while __repr__ aims to be unambiguous.",
                              "print(str(obj) vs repr(obj))", "True",
                              "Display string vs developer debugging string.", "__repr__ often looks like valid Python code.",
                              "True: __str__ provides an informal user representation, whereas __repr__ provides an unambiguous code representation.")
            ],
            "2": [
                create_bool_q("Decorators wrap a function and can modify its arguments, return value, or behavior.",
                              "@my_decorator\ndef greet(): pass", "True",
                              "Decorators are higher-order functions.", "Takes function and returns wrapped function.",
                              "True: Decorators are callables that take a function and return an augmented wrapper callable."),
                create_bool_q("The 'nonlocal' keyword allows modifying a variable in the global module namespace.",
                              "def outer():\n    nonlocal global_var", "False",
                              "Which keyword modifies module-level global variables?", "global modifies globals; nonlocal modifies outer functions.",
                              "False: 'global' modifies module-level variables; 'nonlocal' binds to the nearest enclosing non-global scope."),
                create_bool_q("Decorating a function with @functools.wraps preserves the original function's name and docstring.",
                              "@wraps(fn)\ndef wrapper(*args): pass", "True",
                              "Does wraps copy __name__ and __doc__?", "Preserves metadata.",
                              "True: @functools.wraps copies __name__, __doc__, and other introspection metadata to the wrapper."),
                create_bool_q("Functions in Python are first-class citizens and can be stored in lists or passed as arguments.",
                              "funcs = [print, len, abs]", "True",
                              "First-class objects.", "Can be assigned, stored, and passed.",
                              "True: Functions are objects in Python and can be manipulated like any other data type."),
                create_bool_q("A decorator without @functools.wraps will cause the decorated function to report the wrapper's name.",
                              "print(decorated_func.__name__ == 'wrapper')", "True",
                              "Without wraps, __name__ reflects the wrapper.", "Loses original identifier.",
                              "True: Without @wraps, the function's __name__ is replaced by the inner wrapper's name.")
            ],
            "3": [
                create_bool_q("Generator expressions evaluate and store all elements in memory immediately upon creation.",
                              "g = (x * 2 for x in range(1000000))", "False",
                              "Are generator expressions lazy or eager?", "They produce values on-demand.",
                              "False: Generators are lazy iterators that produce elements one at a time on-demand without memory buffering."),
                create_bool_q("Implementing __iter__() and __next__() makes an object conform to the Python Iterator Protocol.",
                              "class MyIterator:\n    def __iter__(self): return self\n    def __next__(self): pass", "True",
                              "Methods required for custom iterators.", "Must raise StopIteration when exhausted.",
                              "True: The Python Iterator Protocol requires __iter__() returning self and __next__() returning items."),
                create_bool_q("The 'with' statement requires the context object to implement __enter__ and __exit__ methods.",
                              "with open('file.txt') as f: pass", "True",
                              "Context manager protocol methods.", "__enter__ and __exit__.",
                              "True: The context management protocol relies on __enter__() and __exit__() methods."),
                create_bool_q("A StopIteration exception raised inside a generator causes the program to crash if unhandled.",
                              "next(empty_gen)", "False",
                              "For-loops handle StopIteration automatically.", "Normal iteration termination signal.",
                              "False: StopIteration is standard iteration protocol used by for-loops and comprehensions to signal completion."),
                create_bool_q("Calling next() on an exhausted generator continues from the beginning.",
                              "g = (x for x in [1]); next(g); next(g)", "False",
                              "Can generators be rewound or reset automatically?", "They are one-pass streams.",
                              "False: Generators cannot be reset or rewound; once exhausted, subsequent next() calls raise StopIteration.")
            ],
            "4": [
                create_bool_q("Python's Global Interpreter Lock (GIL) allows multiple native threads to execute Python bytecode concurrently on multiple CPU cores.",
                              "# Multi-threaded CPU bound tasks", "False",
                              "Does GIL allow parallel bytecode execution?", "Only one thread runs bytecode at a time.",
                              "False: The CPython GIL restricts execution to a single thread running Python bytecode at any given moment."),
                create_bool_q("Variables in Python are references/pointers to objects, not fixed memory slots.",
                              "a = [1, 2]; b = a\nb.append(3)\nprint(a == [1, 2, 3])", "True",
                              "Assignment binds names to references.", "Mutations through one reference affect all references.",
                              "True: Python variables are labels bound to objects in heap memory; assigning copies the reference."),
                create_bool_q("Coroutines defined with 'async def' execute immediately like regular functions when called.",
                              "async def fetch(): pass\nfetch()  # Runs now?", "False",
                              "Calling an async function returns a coroutine object.", "Must be awaited.",
                              "False: Calling an async function returns a coroutine object that must be awaited or scheduled on an event loop."),
                create_bool_q("The 'is' operator compares object identity via their memory address (id).",
                              "print((x is y) == (id(x) == id(y)))", "True",
                              "What does 'is' evaluate internally?", "Compares id() values.",
                              "True: 'x is y' evaluates whether id(x) == id(y), checking if both names reference the identical object."),
                create_bool_q("Small integers from -5 to 256 are pre-allocated and cached (interned) in CPython.",
                              "x = 100; y = 100\nprint(x is y)", "True",
                              "Integer interning optimization in CPython.", "Cached integer singleton pool.",
                              "True: CPython pre-allocates small integers from -5 to 256 for memory and speed optimization.")
            ]
        }
    }

def get_java_validator():
    return {
        "Beginner": {
            "1": [
                create_bool_q("In Java, every application must contain at least one class definition.",
                              "public class Main { ... }", "True",
                              "Java is an object-oriented language.", "Top-level code must reside in a class.",
                              "True: Java strictly enforces that all code and methods reside within a class."),
                create_bool_q("Java is dynamically typed; variable types do not need to be declared.",
                              "x = 10; // in Java", "False",
                              "Does Java check types at compile time?", "Java is statically typed.",
                              "False: Java is statically typed; variables must be declared with their types (e.g., int x = 10;)."),
                create_bool_q("The 'char' primitive type in Java uses 16-bit Unicode characters.",
                              "char c = 'A';", "True",
                              "Java char size in bits.", "16-bit UTF-16 representation.",
                              "True: In Java, char is a 16-bit unsigned type supporting Unicode characters."),
                create_bool_q("In Java, integer division 7 / 2 results in 3.5.",
                              "int result = 7 / 2;", "False",
                              "What happens when two integers are divided?", "Decimals are truncated to integer 3.",
                              "False: Integer division in Java truncates the fractional part, yielding integer 3."),
                create_bool_q("In Java, variable names cannot start with a number.",
                              "int 1stPlace = 1;", "False",
                              "Can identifiers begin with a digit?", "Must begin with letter, $, or _.",
                              "False: Java variable identifiers cannot begin with a numeric digit.")
            ],
            "2": [
                create_bool_q("In Java, Strings are immutable objects.",
                              "String s = \"hello\"; s.toUpperCase();", "True",
                              "Can String objects be mutated in place?", "Methods return a new String.",
                              "True: String objects in Java are immutable; methods return newly allocated strings."),
                create_bool_q("Comparing Strings with '==' always compares their text contents in Java.",
                              "String a = new String(\"test\");\nString b = new String(\"test\");\nboolean eq = (a == b);", "False",
                              "What does '==' compare for objects in Java?", "'==' checks reference equality; use .equals() for content.",
                              "False: '==' compares object references; .equals() must be used to compare text contents."),
                create_bool_q("Java array indices are zero-based, where the first element is at index 0.",
                              "int[] arr = {10, 20};\nint first = arr[0];", "True",
                              "Zero-based indexing.", "First element is at 0.",
                              "True: Java arrays are indexed starting from 0 up to length - 1."),
                create_bool_q("Once initialized, a standard Java array's size can be dynamically expanded.",
                              "int[] arr = new int[5];\narr.length = 10; // Allowed?", "False",
                              "Are primitive array sizes fixed?", "Arrays have fixed length.",
                              "False: Primitive Java arrays have a fixed size allocated at creation; use ArrayList for dynamic sizing."),
                create_bool_q("The .length property on an array is a method call with parentheses (arr.length()).",
                              "int len = arr.length();", "False",
                              "Is length a field or a method on arrays?", "Field for arrays; method for String.",
                              "False: Array length is a public final field (.length), while String uses the .length() method.")
            ],
            "3": [
                create_bool_q("The 'default' label in a switch statement is mandatory and must always be provided.",
                              "switch (x) { case 1: break; }", "False",
                              "Can a switch statement omit default?", "default branch is optional.",
                              "False: The default case in a Java switch statement is optional."),
                create_bool_q("In an if condition, Java permits integers as boolean conditions (e.g., if (1) { }).",
                              "int x = 1;\nif (x) { ... }", "False",
                              "Does Java convert numbers to booleans automatically?", "Java strictly requires boolean expressions.",
                              "False: Java strictly requires boolean expressions in if/while conditions; numbers do not convert to booleans."),
                create_bool_q("The '&&' logical operator uses short-circuit evaluation in Java.",
                              "if (obj != null && obj.isValid())", "True",
                              "If left operand is false, does it evaluate the right?", "Short-circuits safely.",
                              "True: '&&' short-circuits: if the left operand is false, the right operand is never evaluated."),
                create_bool_q("The ternary operator condition ? expr1 : expr2 is valid syntax in Java.",
                              "int max = (a > b) ? a : b;", "True",
                              "Inline conditional operator.", "condition ? val1 : val2.",
                              "True: Java supports the ternary conditional operator for compact conditional assignments."),
                create_bool_q("In a switch statement without 'break', execution falls through to subsequent cases.",
                              "case 1: doSomething(); case 2: doMore();", "True",
                              "Fallthrough behavior in switch.", "Missing break causes fallthrough.",
                              "True: Without a break statement, control falls through to execute statements in the following case.")
            ],
            "4": [
                create_bool_q("A method declared with 'void' return type cannot return any value.",
                              "public void calculate() { return 42; }", "False",
                              "Can void methods return data?", "Compile-time error.",
                              "False: A void method cannot return a value; attempting to return a value causes a compilation error."),
                create_bool_q("A class constructor in Java can have a return type specified (e.g. public void MyClass()).",
                              "public void MyClass() { }", "False",
                              "Do constructors have return types?", "Constructors have no return type.",
                              "False: Constructors have no return type; adding void turns it into a regular method with the same name."),
                create_bool_q("Multiple methods in the same class can have the same name if their parameter lists differ (overloading).",
                              "public int add(int a, int b) { ... }\npublic double add(double a, double b) { ... }", "True",
                              "Method overloading definition.", "Same name, different parameters.",
                              "True: Method overloading permits multiple methods with the same name but distinct parameter signatures."),
                create_bool_q("Primitive types in Java (int, double, boolean) are stored directly on the stack.",
                              "int x = 100;", "True",
                              "Primitive memory storage.", "Stored on stack as raw values.",
                              "True: Local primitive variables hold their values directly on the stack rather than heap references."),
                create_bool_q("The 'this' keyword refers to the current object instance in Java.",
                              "this.name = name;", "True",
                              "Reference to current instance.", "Disambiguates instance fields.",
                              "True: 'this' is a reference to the current object instance.")
            ]
        },
        "Intermediate": {
            "1": [
                create_bool_q("A class marked as 'final' in Java cannot be extended (subclassed).",
                              "public final class String { ... }", "True",
                              "What does final mean on a class?", "Prevents inheritance.",
                              "True: A final class cannot be extended by any other class."),
                create_bool_q("A subclass inherits private fields and methods directly from its superclass.",
                              "class Child extends Parent { // access private parent field? }", "False",
                              "Are private members visible to subclasses?", "private is restricted to declaring class.",
                              "False: Subclasses do not inherit private members; private restricts visibility strictly to the declaring class."),
                create_bool_q("The 'super()' call to invoke a parent constructor must be the first statement in a constructor.",
                              "public Child() { int x = 1; super(); }", "False",
                              "Position of super() in constructor body.", "Must be the very first statement.",
                              "False: super() must be the very first statement in the constructor; placing code before it causes a compiler error."),
                create_bool_q("Java interfaces can contain method implementations using the 'default' keyword (Java 8+).",
                              "public interface Greeter { default void sayHi() { ... } }", "True",
                              "Default interface methods in Java 8.", "Allows concrete methods in interfaces.",
                              "True: Java 8 introduced default methods in interfaces, allowing interfaces to provide method implementations."),
                create_bool_q("An abstract class can be directly instantiated with the 'new' keyword.",
                              "Shape s = new Shape(); // where Shape is abstract", "False",
                              "Can abstract classes be instantiated directly?", "Cannot instantiate abstract classes.",
                              "False: Abstract classes cannot be instantiated directly; only concrete subclasses can be instantiated.")
            ],
            "2": [
                create_bool_q("ArrayList maintains insertion order and allows duplicate elements.",
                              "List<String> list = new ArrayList<>();", "True",
                              "List contract properties.", "Ordered collection allowing duplicates.",
                              "True: List implementations like ArrayList preserve insertion order and permit duplicate elements."),
                create_bool_q("HashSet in Java maintains elements in the exact order they were inserted.",
                              "Set<Integer> set = new HashSet<>();", "False",
                              "Does HashSet guarantee ordering?", "HashSet is unordered; LinkedHashSet preserves order.",
                              "False: HashSet does not guarantee any order of elements; use LinkedHashSet for insertion order."),
                create_bool_q("HashMap allows multiple NULL values, but at most one NULL key.",
                              "Map<String, String> map = new HashMap<>();", "True",
                              "Null keys and values in HashMap.", "At most one null key permitted.",
                              "True: HashMap allows a single null key and any number of null values."),
                create_bool_q("Autoboxing automatically converts primitive types to their corresponding wrapper classes (e.g. int to Integer).",
                              "Integer num = 5;", "True",
                              "Automatic primitive-to-wrapper conversion.", "int autoboxes to Integer.",
                              "True: Autoboxing is the automatic compiler conversion between primitive types and their wrapper classes."),
                create_bool_q("Iterating over an ArrayList with an enhanced for-loop while calling list.remove() throws ConcurrentModificationException.",
                              "for (String s : list) { list.remove(s); }", "True",
                              "Fail-fast iterator behavior.", "Throws ConcurrentModificationException.",
                              "True: Modifying a collection while iterating via enhanced for-loop triggers a ConcurrentModificationException.")
            ],
            "3": [
                create_bool_q("Checked exceptions in Java must be either caught with try-catch or declared with 'throws'.",
                              "public void readFile() throws IOException { ... }", "True",
                              "Compile-time enforcement of checked exceptions.", "Must be handled or declared.",
                              "True: Java enforces that checked exceptions (subclasses of Exception excluding RuntimeException) be handled or declared."),
                create_bool_q("NullPointerException is a checked exception that must be declared with a throws clause.",
                              "public void doWork() throws NullPointerException", "False",
                              "Is NPE checked or unchecked?", "Unchecked RuntimeException.",
                              "False: NullPointerException extends RuntimeException and is an unchecked exception, so handling is not enforced at compile time."),
                create_bool_q("The 'finally' block in a try-catch-finally construct always executes even if a return statement is encountered in try.",
                              "try { return 1; } finally { System.out.println(\"Runs!\"); }", "True",
                              "Guaranteed execution of finally.", "Runs before return unwinds.",
                              "True: The finally block executes even when a return statement is encountered in the try or catch block."),
                create_bool_q("Multiple catch blocks must order exception types from most specific (subclass) to most general (superclass).",
                              "catch (FileNotFoundException e) { ... } catch (IOException e) { ... }", "True",
                              "Exception hierarchy ordering in catch blocks.", "Specific before general.",
                              "True: Specific exception subclasses must be caught before their general parent classes to avoid unreachable code errors."),
                create_bool_q("The try-with-resources statement automatically closes resources implementing AutoCloseable.",
                              "try (BufferedReader br = new BufferedReader(...)) { ... }", "True",
                              "Automatic resource management.", "AutoCloseable interface.",
                              "True: try-with-resources automatically closes all opened resources implementing AutoCloseable at block completion.")
            ],
            "4": [
                create_bool_q("Anonymous inner classes in Java can access enclosing local variables only if they are final or effectively final.",
                              "int count = 10; Runnable r = () -> System.out.println(count);", "True",
                              "Effectively final requirement for lambda / inner class captures.", "Cannot mutate captured locals.",
                              "True: Local variables referenced inside anonymous classes or lambdas must be final or effectively final."),
                create_bool_q("The equals() and hashCode() methods in Java must be kept consistent with each other.",
                              "if (a.equals(b)) assert a.hashCode() == b.hashCode();", "True",
                              "The hashCode contract.", "Equal objects must have equal hashCodes.",
                              "True: The contract states that if two objects are equal according to equals(), they must produce identical hashCodes."),
                create_bool_q("Static variables in a class are shared across all instances of that class.",
                              "public static int count = 0;", "True",
                              "Class-level variables.", "Single shared copy in memory.",
                              "True: Static variables belong to the class itself and are shared among all instances."),
                create_bool_q("Java supports operator overloading for user-defined classes like C++ does.",
                              "Complex c3 = c1 + c2;", "False",
                              "Can developers overload + or - in Java?", "Java does not support operator overloading.",
                              "False: Java does not allow user-defined operator overloading (the + operator is only overloaded internally for String)."),
                create_bool_q("Generics in Java use type erasure, meaning generic type parameters are removed at runtime.",
                              "List<String> and List<Integer> share same runtime Class object.", "True",
                              "Type erasure mechanism.", "Generic types erased to Object or bounds.",
                              "True: Java generics employ type erasure, removing parameterized type arguments at runtime for backwards compatibility.")
            ]
        },
        "Advanced": {
            "1": [
                create_bool_q("The 'volatile' keyword in Java guarantees atomicity of compound operations like count++.",
                              "private volatile int count = 0;\ncount++;", "False",
                              "Does volatile provide atomicity or memory visibility?", "Provides visibility, not atomicity.",
                              "False: volatile guarantees visibility of updates across threads, but does NOT make compound operations like count++ atomic."),
                create_bool_q("Calling Thread.run() starts execution on a new background thread.",
                              "Thread t = new Thread(); t.run();", "False",
                              "Which method spawns a new thread?", "start() spawns; run() executes on calling thread.",
                              "False: Calling t.run() merely executes the method synchronously on the current thread; t.start() spawns the new thread."),
                create_bool_q("The 'synchronized' keyword on an instance method acquires the monitor lock of the 'this' instance.",
                              "public synchronized void update() { ... }", "True",
                              "Intrinsic monitor lock.", "Locks on 'this'.",
                              "True: Synchronized instance methods acquire the intrinsic monitor lock of the object on which they are invoked."),
                create_bool_q("Deadlock occurs when two or more threads are blocked forever, each waiting for locks held by the other.",
                              "Thread 1 holds A, waits for B; Thread 2 holds B, waits for A.", "True",
                              "Classic circular lock dependency.", "Mutual blocking condition.",
                              "True: Deadlock is a state where concurrent threads are permanently stalled waiting for resources held by one another."),
                create_bool_q("AtomicInteger in java.util.concurrent uses non-blocking Compare-And-Swap (CAS) CPU instructions.",
                              "AtomicInteger ai = new AtomicInteger(); ai.incrementAndGet();", "True",
                              "Lock-free concurrency primitives.", "CAS operations.",
                              "True: AtomicInteger achieves thread safety without mutex locks via hardware-level Compare-And-Swap instructions.")
            ],
            "2": [
                create_bool_q("Java Stream operations are divided into intermediate operations (lazy) and terminal operations (eager).",
                              "list.stream().filter(x -> x > 0).collect(Collectors.toList());", "True",
                              "Stream pipeline lifecycle.", "Intermediate ops are lazy.",
                              "True: Intermediate operations (filter, map) are lazy and only execute when a terminal operation (collect, count) is invoked."),
                create_bool_q("A Java Stream can be reused and traversed multiple times after a terminal operation has executed.",
                              "Stream<String> s = list.stream(); s.count(); s.forEach(...);", "False",
                              "Can streams be consumed twice?", "Throws IllegalStateException: stream has already been operated upon.",
                              "False: A stream is consumed upon executing a terminal operation and cannot be reused; attempting to do so throws an exception."),
                create_bool_q("Functional interfaces in Java are interfaces with exactly one abstract method.",
                              "@FunctionalInterface public interface Task { void execute(); }", "True",
                              "SAM (Single Abstract Method) type.", "Target for lambdas.",
                              "True: A functional interface has exactly one abstract method and can be implemented via lambda expressions."),
                create_bool_q("Optional.of(null) safely creates an empty Optional without throwing an exception.",
                              "Optional<String> opt = Optional.of(null);", "False",
                              "Which method handles nullable references?", "of() throws NullPointerException; ofNullable() allows null.",
                              "False: Optional.of(null) immediately throws a NullPointerException; use Optional.ofNullable(null) for nullable values."),
                create_bool_q("Parallel streams in Java utilize the common ForkJoinPool by default.",
                              "list.parallelStream().forEach(...);", "True",
                              "Underlying thread pool for parallel streams.", "ForkJoinPool.commonPool().",
                              "True: Parallel streams partition workloads across the common ForkJoinPool.")
            ],
            "3": [
                create_bool_q("The Java Reflection API allows accessing private fields of an object using setAccessible(true).",
                              "field.setAccessible(true);", "True",
                              "Can reflection inspect and mutate private state?", "Bypasses access controls.",
                              "True: Java reflection can bypass standard visibility checks using field.setAccessible(true)."),
                create_bool_q("ClassLoader in Java loads classes into memory on-demand when they are first referenced.",
                              "Class.forName(\"com.example.App\");", "True",
                              "Lazy classloading in JVM.", "Loaded dynamically on-demand.",
                              "True: The JVM classloader loads bytecodes into the Metaspace lazily on-demand upon first reference."),
                create_bool_q("Custom annotations in Java with @Retention(RetentionPolicy.SOURCE) are available via reflection at runtime.",
                              "@Retention(RetentionPolicy.SOURCE) public @interface Marker { }", "False",
                              "Which retention policy is kept at runtime?", "RUNTIME retention is required for reflection.",
                              "False: SOURCE retention annotations are discarded by the compiler; RUNTIME retention is required for reflection."),
                create_bool_q("Garbage Collection in Java guarantees that an object will be collected immediately when it becomes unreachable.",
                              "obj = null; System.gc();", "False",
                              "Can you force immediate garbage collection?", "System.gc() is only a hint, not a guarantee.",
                              "False: Garbage Collection runs non-deterministically; System.gc() only requests collection and offers no guarantees."),
                create_bool_q("WeakReference objects do not prevent their referents from being reclaimed by the Garbage Collector.",
                              "WeakReference<Object> ref = new WeakReference<>(new Object());", "True",
                              "Weak reference behavior during GC.", "Collected on next GC cycle.",
                              "True: Objects referenced solely by weak references are reclaimed during the next garbage collection cycle.")
            ],
            "4": [
                create_bool_q("In the JVM memory model, objects are allocated in Heap memory while method call frames reside on the Thread Stack.",
                              "Heap vs Stack memory division.", "True",
                              "Where are instances stored vs local frames?", "Heap stores objects; Stack stores call frames.",
                              "True: In the JVM, dynamic object instances live in Heap space, while method call frames and local references live on Thread Stacks."),
                create_bool_q("Java's 'transient' keyword prevents a field from being serialized when an object is written to an ObjectOutputStream.",
                              "private transient String secretKey;", "True",
                              "Serialization keyword.", "Skips marked fields during serialization.",
                              "True: Fields marked with 'transient' are skipped by the Java serialization engine."),
                create_bool_q("The Metaspace in Java 8+ is allocated in native OS memory rather than inside the contiguous Java Heap.",
                              "Metaspace replacement of PermGen.", "True",
                              "PermGen vs Metaspace in Java 8.", "Allocated out of native memory.",
                              "True: In Java 8, PermGen was replaced by Metaspace, which dynamically allocates from native process memory."),
                create_bool_q("Java allows multiple inheritance of state (inheriting instance fields from multiple classes).",
                              "class D extends B, C { }", "False",
                              "Can a Java class inherit state from multiple classes?", "Java forbids multiple class inheritance.",
                              "False: Java does not allow extending multiple classes; it only supports multiple interface implementation."),
                create_bool_q("The Java Memory Model ensures that final fields of an object are safely published and visible to other threads once constructor completes.",
                              "final fields in immutable objects.", "True",
                              "Safe publication of final fields.", "JMM guarantee.",
                              "True: The Java Memory Model guarantees that properly initialized final fields are visible to all threads without explicit locking.")
            ]
        }
    }

def get_sql_validator():
    return {
        "Beginner": {
            "1": [
                create_bool_q("In SQL, keywords like SELECT and FROM are strictly case-sensitive.",
                              "select * from users; vs SELECT * FROM users;", "False",
                              "Are SQL keywords case-sensitive?", "SQL is case-insensitive for standard keywords.",
                              "False: SQL keywords are case-insensitive; SELECT, select, and Select are interpreted identically."),
                create_bool_q("The WHERE clause is required in every valid SQL SELECT statement.",
                              "SELECT * FROM products;", "False",
                              "Can you query an entire table without WHERE?", "WHERE is optional.",
                              "False: The WHERE clause is completely optional; omitting it returns all rows in the table."),
                create_bool_q("String literals in standard SQL are enclosed in single quotes ('text').",
                              "SELECT * FROM users WHERE status = 'active';", "True",
                              "Quote conventions in ANSI SQL.", "Single quotes for values.",
                              "True: Standard SQL string literals must be enclosed in single quotes ('example')."),
                create_bool_q("In SQL, the asterisk (*) wildcard projects all columns from the referenced table.",
                              "SELECT * FROM employees;", "True",
                              "Meaning of * in SELECT projection.", "Expands to all columns.",
                              "True: The asterisk (*) wildcard instructs the database to return all columns from the source relation."),
                create_bool_q("The comparison operator for equality in SQL is single '=' (not '==').",
                              "WHERE age = 21", "True",
                              "SQL equality operator.", "Single equal sign.",
                              "True: Standard SQL uses a single '=' to check for equality.")
            ],
            "2": [
                create_bool_q("ORDER BY sorts query results in ascending order (ASC) by default if unspecified.",
                              "SELECT * FROM items ORDER BY price;", "True",
                              "Default direction of ORDER BY.", "ASC is the default.",
                              "True: If neither ASC nor DESC is specified, ORDER BY defaults to ascending order."),
                create_bool_q("The LIMIT clause in SQLite/Postgres filters rows before the WHERE clause is evaluated.",
                              "SELECT * FROM t WHERE id > 10 LIMIT 5;", "False",
                              "Query execution order.", "WHERE filters rows first; LIMIT caps the output at the end.",
                              "False: WHERE filters rows early during table scans; LIMIT is applied at the very end of query execution."),
                create_bool_q("The AND operator requires BOTH conditions to evaluate to true for a row to be included.",
                              "WHERE active = 1 AND age >= 18", "True",
                              "Logical conjunction.", "Both must be true.",
                              "True: Logical AND demands that both left and right expressions be true."),
                create_bool_q("The expression 'price BETWEEN 10 AND 20' is exclusive of the boundary values 10 and 20.",
                              "WHERE price BETWEEN 10 AND 20", "False",
                              "Is BETWEEN inclusive or exclusive?", "BETWEEN is inclusive.",
                              "False: SQL BETWEEN is inclusive of both boundary endpoints (equivalent to price >= 10 AND price <= 20)."),
                create_bool_q("In SQL LIKE patterns, the percent symbol '%' matches zero or more characters.",
                              "WHERE name LIKE 'J%'", "True",
                              "Multi-character wildcard.", "% matches any character sequence.",
                              "True: The '%' wildcard matches any sequence of zero, one, or more characters in LIKE expressions.")
            ],
            "3": [
                create_bool_q("Evaluating 'NULL = NULL' in SQL returns TRUE.",
                              "SELECT NULL = NULL;", "False",
                              "Three-Valued Logic in SQL.", "Comparisons with NULL yield UNKNOWN/falsy.",
                              "False: In SQL Three-Valued Logic, comparing with NULL using '=' evaluates to UNKNOWN, not TRUE."),
                create_bool_q("To check if a column contains a missing value, you must use 'IS NULL'.",
                              "SELECT * FROM users WHERE email IS NULL;", "True",
                              "Testing for NULL.", "IS NULL operator.",
                              "True: IS NULL (and IS NOT NULL) is the proper ANSI SQL operator to check for missing/null values."),
                create_bool_q("An UPDATE statement without a WHERE clause updates every single row in the target table.",
                              "UPDATE accounts SET balance = 0;", "True",
                              "What happens without WHERE?", "Applies mutation to all records.",
                              "True: Omitting the WHERE clause in an UPDATE statement modifies all rows in the entire table."),
                create_bool_q("A DELETE statement without a WHERE clause drops the table schema from the database.",
                              "DELETE FROM customers;", "False",
                              "Does DELETE drop the table definition?", "DELETE removes rows; DROP TABLE removes schema.",
                              "False: DELETE FROM removes all data rows but leaves the table structure intact; DROP TABLE removes the schema."),
                create_bool_q("The INSERT INTO statement can insert multiple rows in a single query.",
                              "INSERT INTO t (col) VALUES (1), (2), (3);", "True",
                              "Multi-row insert syntax.", "Comma-separated value tuples.",
                              "True: Multi-row insert syntax allows appending multiple tuple sets separated by commas.")
            ],
            "4": [
                create_bool_q("The COUNT(*) function counts all rows in a group, including rows containing NULLs.",
                              "SELECT COUNT(*) FROM users;", "True",
                              "COUNT(*) vs COUNT(column).", "Counts all rows regardless of column nullability.",
                              "True: COUNT(*) tallies all rows in the relation/group, regardless of whether individual columns contain NULL."),
                create_bool_q("The COUNT(column_name) function includes NULL values in its calculation.",
                              "SELECT COUNT(email) FROM users;", "False",
                              "Does COUNT(col) count nulls?", "Skips NULL values.",
                              "False: COUNT(column_name) only tallies rows where the specified column is NOT NULL."),
                create_bool_q("Aggregate functions like SUM() and AVG() automatically ignore NULL values.",
                              "SELECT AVG(score) FROM scores; -- scores: (10, NULL, 20)", "True",
                              "Handling of NULL in numeric aggregates.", "NULLs are skipped.",
                              "True: Standard numeric aggregate functions (SUM, AVG, MIN, MAX) automatically ignore NULL values."),
                create_bool_q("The AS keyword creates a permanent column rename in the underlying database table.",
                              "SELECT price AS cost FROM products;", "False",
                              "Is AS permanent or temporary for output?", "Alias is query-scoped.",
                              "False: The AS keyword assigns a temporary alias for query output projection; it does not alter table schema."),
                create_bool_q("The MAX() function works on string and date columns, not only numbers.",
                              "SELECT MAX(name), MAX(hire_date) FROM employees;", "True",
                              "Can MAX evaluate lexicographical or chronological order?", "Works on ordered types.",
                              "True: MAX() and MIN() work on any ordered data type including strings (alphabetical) and dates.")
            ]
        },
        "Intermediate": {
            "1": [
                create_bool_q("The HAVING clause can be used to filter rows based on aggregate expressions like COUNT(*) > 5.",
                              "SELECT dept, COUNT(*) FROM emp GROUP BY dept HAVING COUNT(*) > 5;", "True",
                              "Can HAVING evaluate aggregates?", "HAVING filters groups post-aggregation.",
                              "True: HAVING filters groups using aggregate functions, which cannot be used in WHERE."),
                create_bool_q("The WHERE clause can directly filter on aggregate functions, e.g. WHERE AVG(salary) > 50000.",
                              "SELECT dept FROM emp WHERE AVG(salary) > 50000 GROUP BY dept;", "False",
                              "Can aggregates appear in WHERE?", "Aggregates are forbidden in WHERE.",
                              "False: Aggregate functions cannot appear in the WHERE clause; they must be evaluated in HAVING."),
                create_bool_q("Every non-aggregated column in the SELECT clause must appear in the GROUP BY clause in standard SQL.",
                              "SELECT dept, job_title, COUNT(*) FROM emp GROUP BY dept;", "True",
                              "ANSI SQL GROUP BY requirement.", "All non-aggregates must be grouped.",
                              "True: In standard SQL, all non-aggregated columns in SELECT must be listed in GROUP BY."),
                create_bool_q("The DISTINCT keyword can be used inside aggregate functions, such as COUNT(DISTINCT country).",
                              "SELECT COUNT(DISTINCT country) FROM customers;", "True",
                              "Counting unique values.", "COUNT(DISTINCT col).",
                              "True: DISTINCT can be placed inside aggregate functions to compute metrics over unique values only."),
                create_bool_q("The GROUP BY clause is executed after the ORDER BY clause in query execution flow.",
                              "FROM -> WHERE -> GROUP BY -> HAVING -> SELECT -> ORDER BY", "False",
                              "Logical query execution order.", "GROUP BY runs before ORDER BY.",
                              "False: GROUP BY executes before SELECT and ORDER BY; ORDER BY is one of the final execution steps.")
            ],
            "2": [
                create_bool_q("An INNER JOIN returns only records where there is a matching row in both tables.",
                              "SELECT * FROM a INNER JOIN b ON a.id = b.a_id;", "True",
                              "Intersection join.", "Matches required in both sets.",
                              "True: INNER JOIN selects records that have matching values in both linked relations."),
                create_bool_q("A LEFT JOIN includes all records from the right table even if there is no match in the left table.",
                              "SELECT * FROM customers LEFT JOIN orders ON ...;", "False",
                              "Which table is preserved in LEFT JOIN?", "The LEFT table is preserved.",
                              "False: LEFT JOIN preserves all rows from the left table; unmatched right-side columns are filled with NULL."),
                create_bool_q("A CROSS JOIN between a table with 5 rows and a table with 4 rows produces 20 rows.",
                              "SELECT * FROM tableA CROSS JOIN tableB;", "True",
                              "Cartesian product multiplication: 5 * 4.", "5 * 4 = 20.",
                              "True: CROSS JOIN computes the Cartesian product, multiplying the row counts: 5 * 4 = 20."),
                create_bool_q("A table can be joined to itself (self-join) by using distinct table aliases.",
                              "SELECT e.name, m.name FROM emp e JOIN emp m ON e.mgr_id = m.id;", "True",
                              "Self-join using aliases.", "Hierarchical relationships.",
                              "True: A self-join joins a table to itself using separate aliases to distinguish roles."),
                create_bool_q("In a LEFT JOIN, unmatched rows from the right table are filled with the integer 0.",
                              "Unmatched right columns in LEFT JOIN.", "False",
                              "What fills missing fields in outer joins?", "Filled with NULL, not 0.",
                              "False: Unmatched columns in outer joins evaluate to NULL, not 0.")
            ],
            "3": [
                create_bool_q("The 'IN' operator is functionally equivalent to multiple OR conditions chained together.",
                              "status IN ('A', 'B') vs status = 'A' OR status = 'B'", "True",
                              "Set membership equivalence.", "Equivalent to OR list.",
                              "True: 'x IN (a, b)' is logically identical to 'x = a OR x = b'."),
                create_bool_q("A subquery that returns multiple rows can be compared using the '=' operator.",
                              "WHERE salary = (SELECT salary FROM employees);", "False",
                              "Can scalar '=' compare against multiple rows?", "Causes subquery returned more than 1 row error.",
                              "False: Single-value comparison operators (=, <, >) require scalar subqueries returning exactly 1 row."),
                create_bool_q("The EXISTS operator stops searching as soon as it finds the first matching row (short-circuit).",
                              "WHERE EXISTS (SELECT 1 FROM orders WHERE user_id = u.id)", "True",
                              "Short-circuit evaluation of EXISTS.", "Stops on first match.",
                              "True: EXISTS returns TRUE immediately upon encountering the first qualifying row in the subquery."),
                create_bool_q("If a subquery evaluated by 'NOT IN' returns even a single NULL value, the entire NOT IN condition yields UNKNOWN / no rows.",
                              "WHERE id NOT IN (1, 2, NULL)", "True",
                              "Three-valued logic hazard with NOT IN.", "NULL in NOT IN breaks condition.",
                              "True: If any subquery value is NULL, NOT IN evaluates to UNKNOWN for non-matching rows, returning zero results."),
                create_bool_q("A correlated subquery is evaluated once for the entire query rather than once per candidate row.",
                              "WHERE salary > (SELECT AVG(salary) FROM emp e2 WHERE e2.dept = e1.dept)", "False",
                              "Correlated subquery execution.", "Evaluates for each outer row.",
                              "False: A correlated subquery references values from the outer query and must be evaluated once per candidate row.")
            ],
            "4": [
                create_bool_q("UNION ALL executes faster than UNION because it skips duplicate elimination.",
                              "SELECT id FROM a UNION ALL SELECT id FROM b;", "True",
                              "Deduplication overhead in UNION.", "UNION ALL avoids sorting/hashing.",
                              "True: UNION ALL preserves duplicates without sorting or hashing, making it significantly faster than UNION."),
                create_bool_q("A CASE statement in SQL can be used inside aggregate functions, e.g. SUM(CASE WHEN ... THEN 1 ELSE 0 END).",
                              "SELECT SUM(CASE WHEN active = 1 THEN 1 ELSE 0 END) FROM users;", "True",
                              "Conditional aggregation pattern.", "Pivoting data.",
                              "True: Nesting CASE inside SUM/COUNT is the standard pattern for conditional aggregation and pivoting."),
                create_bool_q("A SQL View permanently stores a duplicate copy of the underlying table data on disk.",
                              "CREATE VIEW active_users AS SELECT * FROM users WHERE active = 1;", "False",
                              "Are standard views virtual or materialized?", "Views are virtual query definitions.",
                              "False: Standard SQL views are virtual tables that execute their query on-the-fly without storing duplicate data."),
                create_bool_q("In a CASE statement, the ELSE branch is mandatory; omitting it causes a syntax error.",
                              "CASE WHEN x = 1 THEN 'A' END", "False",
                              "Is ELSE required in CASE?", "Defaults to NULL if omitted.",
                              "False: The ELSE clause is optional; if omitted and no WHEN condition matches, the expression returns NULL."),
                create_bool_q("To combine two queries with UNION, both queries must select the same number of compatible columns.",
                              "SELECT id, name FROM a UNION SELECT id, title FROM b;", "True",
                              "UNION schema compatibility requirements.", "Matching column counts and types.",
                              "True: UNION requires both participating queries to project the same number of columns with compatible data types.")
            ]
        },
        "Advanced": {
            "1": [
                create_bool_q("Window functions do NOT collapse rows into a single summary row like GROUP BY does.",
                              "SELECT id, SUM(amount) OVER () FROM orders;", "True",
                              "Difference between windowing and GROUP BY.", "Maintains original row identity.",
                              "True: Unlike GROUP BY, window functions perform calculations across sets of rows while retaining each individual row."),
                create_bool_q("DENSE_RANK() leaves gaps in the ranking sequence when there are ties (e.g., 1, 2, 2, 4).",
                              "DENSE_RANK() OVER (ORDER BY score DESC)", "False",
                              "Which ranking function leaves gaps vs no gaps?", "RANK leaves gaps; DENSE_RANK leaves no gaps.",
                              "False: RANK() leaves gaps after ties (1, 2, 2, 4), while DENSE_RANK() produces gapless ranks (1, 2, 2, 3)."),
                create_bool_q("The LAG() window function accesses data from a previous row within the window partition.",
                              "LAG(revenue, 1) OVER (ORDER BY date)", "True",
                              "Accessing prior rows.", "LAG looks back.",
                              "True: LAG(column, offset) accesses data from preceding rows without requiring a self-join."),
                create_bool_q("Window functions can be placed inside the WHERE clause to filter rows directly.",
                              "SELECT * FROM emp WHERE ROW_NUMBER() OVER (ORDER BY salary) = 1;", "False",
                              "Can window functions appear in WHERE?", "Must use a subquery or CTE to filter window functions.",
                              "False: Window functions execute after WHERE/HAVING and cannot be placed in the WHERE clause directly."),
                create_bool_q("PARTITION BY inside an OVER clause resets the window function calculation for each group.",
                              "ROW_NUMBER() OVER (PARTITION BY dept_id ORDER BY hire_date)", "True",
                              "What does PARTITION BY do in window specs?", "Resets calculations per partition.",
                              "True: PARTITION BY divides rows into partitions where window calculations execute and reset independently.")
            ],
            "2": [
                create_bool_q("A Common Table Expression (CTE) defined with WITH is temporary and only exists for the duration of the query.",
                              "WITH TempCTE AS (SELECT * FROM t) SELECT * FROM TempCTE;", "True",
                              "Lifecycle of a CTE.", "Scope is restricted to single statement.",
                              "True: CTEs are query-scoped temporary named result sets that exist only during the execution of that statement."),
                create_bool_q("Recursive CTEs require an anchor member and a recursive member joined by UNION or UNION ALL.",
                              "WITH RECURSIVE Seq AS (SELECT 1 UNION ALL SELECT n+1 FROM Seq WHERE n < 5)", "True",
                              "Structure of recursive CTE.", "Base case + recursive step.",
                              "True: Recursive CTEs consist of an anchor member (base case) and a recursive member joined by UNION / UNION ALL."),
                create_bool_q("A single query can define multiple CTEs separated by commas under a single 'WITH' keyword.",
                              "WITH a AS (...), b AS (...) SELECT * FROM a JOIN b ON ...;", "True",
                              "Chaining CTEs.", "Single leading WITH keyword.",
                              "True: Multiple CTEs can be defined sequentially separated by commas following a single WITH keyword."),
                create_bool_q("Recursive CTEs automatically detect and prevent infinite loops without needing termination conditions.",
                              "WITH RECURSIVE Loop AS (SELECT 1 UNION ALL SELECT n FROM Loop) ...", "False",
                              "What happens if recursion has no termination condition?", "Runs until recursion limit or crashes.",
                              "False: Recursive CTEs require explicit termination conditions (WHERE clause); otherwise they loop until hitting recursion limits."),
                create_bool_q("A CTE can reference another CTE defined prior to it within the same WITH statement.",
                              "WITH a AS (...), b AS (SELECT * FROM a) SELECT * FROM b;", "True",
                              "Referencing earlier CTEs.", "Sequential dependency allowed.",
                              "True: Subsequent CTEs can freely reference earlier CTEs defined within the same WITH block.")
            ],
            "3": [
                create_bool_q("A database transaction guarantees that either ALL modifications are committed or ALL are rolled back (Atomicity).",
                              "BEGIN; UPDATE a; UPDATE b; COMMIT;", "True",
                              "The 'A' in ACID.", "All or nothing.",
                              "True: Atomicity ensures that all operations in a transaction succeed together or none take effect."),
                create_bool_q("Adding an index to a column always speeds up both SELECT and INSERT operations.",
                              "CREATE INDEX idx_col ON tbl(col);", "False",
                              "Does an index speed up writes/inserts?", "Slows down INSERT/UPDATE because index must be updated.",
                              "False: Indexes speed up read (SELECT) operations but introduce write overhead on INSERT, UPDATE, and DELETE."),
                create_bool_q("Foreign key constraints with ON DELETE CASCADE automatically delete related child rows when the parent is deleted.",
                              "FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE", "True",
                              "Cascading deletion behavior.", "Removes orphaned child records.",
                              "True: ON DELETE CASCADE automatically removes child records referencing a deleted parent key."),
                create_bool_q("The ROLLBACK command can undo a transaction even after COMMIT has already been executed.",
                              "COMMIT; ROLLBACK;", "False",
                              "Can committed data be rolled back?", "COMMIT is permanent (Durability).",
                              "False: Once a transaction is committed, changes are permanently written and cannot be undone with ROLLBACK."),
                create_bool_q("A UNIQUE constraint automatically creates an underlying unique index in most relational databases.",
                              "ALTER TABLE users ADD CONSTRAINT unq_email UNIQUE(email);", "True",
                              "Implementation of UNIQUE constraints.", "Backed by a unique index.",
                              "True: Databases create a unique index to enforce UNIQUE constraint validation efficiently.")
            ],
            "4": [
                create_bool_q("COALESCE() evaluates and returns the first non-NULL expression from its list of arguments.",
                              "SELECT COALESCE(NULL, NULL, 'Found', 'Extra');", "True",
                              "Function returning first non-null.", "Returns 'Found'.",
                              "True: COALESCE evaluates its arguments in order and returns the first non-null value."),
                create_bool_q("In SQL, NULL values are indexed and sorted identically across all database engines (always first).",
                              "ORDER BY col ASC -- NULLs position", "False",
                              "Do all databases sort NULLs the same way?", "Varies: Oracle puts NULLs last; SQLite/Postgres can vary or use NULLS FIRST/LAST.",
                              "False: NULL ordering varies across engines (e.g. SQLite sorts NULLs lowest; Oracle sorts NULLs highest unless NULLS FIRST/LAST is set)."),
                create_bool_q("NTILE(4) segments an ordered partition into 4 approximately equal quartile groups.",
                              "NTILE(4) OVER (ORDER BY sales DESC)", "True",
                              "Quartile distribution function.", "Divides rows into 4 buckets.",
                              "True: NTILE(n) divides ordered rows into n approximately equal ranked buckets from 1 to n."),
                create_bool_q("EXPLAIN QUERY PLAN provides diagnostic information on whether queries perform index scans or full table scans.",
                              "EXPLAIN QUERY PLAN SELECT * FROM users WHERE email = 'a@b.com';", "True",
                              "Execution plan diagnostics.", "Index search vs scan.",
                              "True: EXPLAIN QUERY PLAN displays the database query optimizer's planned execution steps and index usage."),
                create_bool_q("A B-Tree index can efficiently optimize queries using LIKE with leading wildcards (e.g. LIKE '%term').",
                              "WHERE name LIKE '%term'", "False",
                              "Can B-Trees search by suffix?", "Leading wildcard forces a full table scan.",
                              "False: Standard B-Tree indexes cannot be used for leading wildcards like '%term' and result in a full table scan.")
            ]
        }
    }
